[package]
name = "revault-gui"
version = "0.0.1"
readme = "README.md"
description = "Revault GUI"
repository = "https://github.com/re-vault/revault-gui"
license = "BSD-3-Clause"
authors = ["Edouard Paris <m@edouard.paris>"]
edition = "2018"

[dependencies]
bitcoin = { version = "0.25.2", features = ["base64", "use-serde"] }

iced = { version = "0.3", features = ["wgpu", "svg", "debug", "qr_code"] }

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
jsonrpc = { git = "https://github.com/darosior/rust-jsonrpc", branch = "moar_transports", features = ["simple_uds"] }

tracing = "0.1"
tracing-subscriber = "0.2"

dirs = "3.0.1"
toml = "0.5"

chrono = "0.4"
